# Generated by Django 3.1.5 on 2021-07-24 19:52

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user', 'email_confirmed']},
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.writer_img_upload_location),
        ),
        migrations.AlterField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
