# Generated by Django 3.1.5 on 2021-05-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210526_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='firstname',
            field=models.CharField(default='fill', max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastname',
            field=models.CharField(default='fill', max_length=30),
        ),
    ]
