# Generated by Django 3.1.5 on 2021-07-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_writer_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Writer_Profile',
            new_name='WriterProfile',
        ),
    ]
