# Generated by Django 3.1.5 on 2021-07-03 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reports',
            field=models.ManyToManyField(blank=True, default=None, related_name='comment_reports', through='blog.CommentReport', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='reports',
            field=models.ManyToManyField(blank=True, default=None, related_name='reply_reports', through='blog.ReplyReport', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='reports',
            field=models.ManyToManyField(blank=True, default=None, related_name='post_reports', through='blog.PostReport', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='replyreport',
            name='reply',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reply_reports', to='blog.reply'),
        ),
    ]
