# Generated by Django 3.1.5 on 2021-05-26 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20210526_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('racism', 'Racism'), ('nudity', 'Nudity')], max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('new', models.BooleanField(default=True)),
                ('good', models.BooleanField(default=True)),
                ('false', models.BooleanField(default=False)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to='blog.blogpost')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reports',
            field=models.ManyToManyField(blank=True, default=None, related_name='reported', through='blog.Report', to=settings.AUTH_USER_MODEL),
        ),
    ]
