# Generated by Django 3.1.5 on 2021-07-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210703_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='title',
            field=models.CharField(choices=[('racism', 'Racism'), ('nudity', 'Nudity'), ('sexual harrasment', 'Sexual harrasment'), ('false information', 'False information'), ('spam', "It's spam"), ('hate speech or symbols', 'Hate speech or symbols'), ('bullying', 'Bullying'), ('scam or fraud', 'Scam or fraud'), ('violence', 'Violence'), ('sale of illegal or regulated goods', 'Sale of illegal or regulated goods')], max_length=50),
        ),
    ]
