# Generated by Django 3.1.5 on 2021-05-26 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20210526_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='reports',
            field=models.ManyToManyField(blank=True, default=None, related_name='reports', through='blog.Report', to=settings.AUTH_USER_MODEL),
        ),
    ]
