# Generated by Django 3.1.5 on 2021-07-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210707_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreport',
            name='good',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='replyreport',
            name='good',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
