# Generated by Django 3.1.5 on 2021-05-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210526_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='false',
            new_name='bad',
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
