# Generated by Django 3.1.5 on 2021-05-26 23:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20210527_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_on', 'replier'], 'verbose_name_plural': 'replies'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='disliked',
            field=models.ManyToManyField(blank=True, default=None, editable=False, related_name='disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, editable=False, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
