# Generated by Django 3.1.5 on 2021-05-27 01:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210527_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=tinymce.models.HTMLField(default='Default'),
        ),
    ]
