# Generated by Django 3.1.5 on 2021-05-27 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210527_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='commentbody',
        ),
    ]
