# Generated by Django 3.1.5 on 2021-05-27 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210527_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentbody',
            new_name='body',
        ),
    ]
