# Generated by Django 3.1.5 on 2021-05-27 21:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210527_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='reply',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
