# Generated by Django 3.1.5 on 2021-06-08 02:51

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210529_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_img',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.author_img_upload_location),
        ),
    ]
