# Generated by Django 3.1.5 on 2021-06-08 08:25

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogpost_author_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author_img',
            field=models.ImageField(default='default', upload_to=blog.models.author_img_upload_location),
            preserve_default=False,
        ),
    ]
